# Generated by Django 2.2.10 on 2020-07-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_elec_heating',
            field=models.BooleanField(default=False, verbose_name='if the client has an eletric heating'),
        ),
    ]
