# Generated by Django 2.2.10 on 2020-07-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_client_has_elec_heating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='has_elec_heating',
            field=models.BooleanField(default=False, verbose_name='If the client has an eletric heating'),
        ),
    ]
